<br /><br />
<div id="view-content">
	<h2>Impressum SoundPuzzle</h2>

	<address>
		<strong>Soundpuzzle</strong>s<br>
		Philip-Alexander Popp<br>
		Behaimstr. 4 <br>
		10585 Berlin<br>
		Telefon: 015778948228<br>
		Fax: nicht vorhanden<br>
		E-Mail: popp.philip@googlemail.com
	</address>

	<p>
		Umsatzsteueridentifikationsnummer: nicht erteilt
		<br><br>
		Inhaltlich Verantwortlicher gem. § 55 Abs.2 RStV:
		Philip-Alexander Popp, Behaimstr. 4, 10585 Berlin
	</p>

	<h3>
		1. Haftungsausschluss
	</h3>
	<p>

		Soundpuzzle übernimmt keinerlei Gewähr für die Aktualität, Korrektheit, Vollständigkeit oder Qualität der bereitgestellten Informationen. Haftungsansprüche gegen Soundpuzzle, welche sich auf Schäden materieller oder ideeller Art beziehen, die durch die Nutzung oder Nichtnutzung der dargebotenen Informationen bzw. durch die Nutzung fehlerhafter und unvollständiger Informationen verursacht wurden, sind grundsätzlich ausgeschlossen, sofern seitens von Soundpuzzle kein nachweislich vorsätzliches oder grob fahrlässiges Verschulden vorliegt.
		Alle Angebote sind freibleibend und unverbindlich. Soundpuzzle behält es sich ausdrücklich vor, Teile der Seiten oder das gesamte Angebot ohne gesonderte Ankündigung zu verändern, zu ergänzen, zu löschen oder die Veröffentlichung zeitweise oder endgültig einzustellen.
	</p>

	<h3>2. Verweise und Verlinkungen</h3>
	<p>Auf den Webseiten von Soundpuzzle sowie den dazugehörigen Unterseiten befinden sich Links zu anderen Seiten im Internet.
		Soundpuzzle erklärt ausdrücklich, dass Soundpuzzle keinen Einfluss auf die Gestaltung und den Inhalt der Seiten hat, auf die von den von Soundpuzzle betriebenen Homepages verlinkt wird. Daher übernimmt Soundpuzzle keine Gewähr für die Richtigkeit, Vollständigkeit, Aktualität, oder Qualität der dort bereitgestellten Informationen und distanziert sich hiermit ausdrücklich von allen Inhalten dieser Seiten. Diese Erklärung gilt für alle von Soundpuzzle betriebenen Webseiten für Links zu externen Seiten und alle Inhalte dieser Seiten, zu denen diese Links führen.
	</p>

	<h3>3. Verwertungshinweis</h3>
	<p>Es ist untersagt, sämtliche angebotenen Informationen, sei es auch nur auszugsweise, ohne schriftliche Genehmigung Soundpuzzle weiterzuverbreiten oder anderweitig zu veröffentlichen.
	</p>
	<h3>4. Urheber- und Kennzeichenrecht</h3>
	<p>Soundpuzzle ist bestrebt, in allen Publikationen die Urheberrechte der verwendeten Grafiken, Tondokumente, Videosequenzen und Texte zu beachten, selbst erstellte Grafiken, Tondokumente, Videosequenzen und Texte zu nutzen oder auf lizenzfreie Grafiken, Tondokumente, Videosequenzen und Texte zurückzugreifen.
		Alle innerhalb des Internetangebotes genannten und ggf. durch Dritte geschützten Marken- und Warenzeichen unterliegen uneingeschränkt den Bestimmungen des jeweils gültigen Kennzeichenrechts und den Besitzrechten der jeweiligen eingetragenen Eigentümer. Allein aufgrund der bloßen Nennung ist nicht der Schluss zu ziehen, dass Markenzeichen nicht durch Rechte Dritter geschützt sind!
		Das Copyright für veröffentlichte, von Soundpuzzle selbst erstellte Objekte bleibt allein bei Soundpuzzle. Eine Vervielfältigung oder Verwendung solcher Grafiken, Tondokumente, Videosequenzen und Texte in anderen elektronischen oder gedruckten Publikationen ist ohne ausdrückliche Zustimmung von Soundpuzzle nicht gestattet.
	</p>
	<h3>5. Keine Abmahnung ohne vorherigen Kontakt</h3>
	<p>Sollte Inhalt oder die design-technische Gestaltung einzelner Seiten oder Teile der Webseiten von Soundpuzzle die Rechte Dritter oder gesetzliche Bestimmungen verletzen oder anderweitig in irgendeiner Form wettbewerbsrechtliche Probleme hervorbringen, so bitten wir um eine angemessene, ausreichend erläuternde und schnelle Nachricht ohne Kostennote. Wir garantieren, dass die zu Recht beanstandeten Passagen oder Teile des Onlinesportals unverzüglich entfernt bzw. den rechtlichen Vorgaben umfänglich angepasst werden, ohne dass von Ihrer Seite die Einschaltung eines Rechtsbeistandes erforderlich ist. Die zeitaufwändigere Einschaltung eines Anwaltes zur für den Dienstanbieter kostenpflichtigen Abmahnung entspricht nicht dessen wirklichen oder mutmaßlichen Willen.
	</p>
</div>