<div class="row">
	<div class="span1 pagination-right">
		<img src="images/layout/fragezeichen.png" alt="Fragezeichen" >
	</div>
	<div class="span4">
		<h2>Was ist <strong>SoundPuzzle</strong>?</h2>
		<p>Auf <strong>Soundpuzzle</strong> erstellen Dir Musiker im Wettbewerb preiswert und individuell den passenden Sound für Dein Musikprojekt.</p>
		<p>Folge uns auf Facebook &nbsp;&nbsp; <iframe src="http://www.facebook.com/plugins/like.php?href=http%3A%2F%2Fwww.soundpuzzle.de&amp;layout=button_count&amp;show_faces=true&amp;width=200&amp;action=like&amp;colorscheme=light&amp;height=20" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:200px; height:20px;position: relative;top:5px;" allowTransparency="true"></iframe></p>
	</div>
	<div class="span4">
		<h2><strong>Jetzt</strong> voranmelden:</h2>
		<a class="btn btn-inverse btn-large span3 lightbox" href="/reminder/type/1" title="Musiker anmelden">Musiker</a>
		<a class="btn btn-inverse btn-large span3 lightbox" href="/reminder/type/2" title="Auftraggeber anmelden">Auftraggeber</a>
	</div>
	<div class="span11 offset1 ">
		<hr>
	</div>
</div>
<div class="row">
	<div class="span1 pagination-right">
		<img src="images/layout/ausrufezeichen.png" alt="Ausrufezeichen" >
	</div>
	<div class="span8">
		<h2 class="special">So funktioniert SoundPuzzle</h2>
	</div>
	<div class="span11 offset1">
		<a rel="solution" href="/index/solution/step/1" title="EINSTELLUNGSPROZESS" class="lightbox">
			<img src="images/layout/player.png" alt="Puzzle Dir deinen Sound" >
		</a>
	</div>
	<a rel="solution" href="/index/solution/step/2" title="SCHUTZ DER MUSIK" class="lightbox hidden">SCHUTZ DER MUSIK</a>
	<a rel="solution" href="/index/solution/step/3" title="DER FINDUNGSPROZESS" class="lightbox hidden">DER FINDUNGSPROZESS</a>
	<a rel="solution" href="/index/solution/step/4" title="AUSWÄHLEN DES SIEGERS" class="lightbox hidden">AUSWÄHLEN DES SIEGERS</a>
	<a rel="solution" href="/index/solution/step/5" title="GELD-ZURÜCK-GARANTIE" class="lightbox hidden">GELD-ZURÜCK-GARANTIE</a>
</div>
