<div class="hero-unit">
	<h1>Puzzle Dir Deinen Sound</h1>
	<p>This is a template for a simple marketing or informational website. It includes a large callout called the hero unit and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
	<div class="row">
		<div class="span1 offset4"><a class="btn btn-inverse btn-large lightbox" href="/remindMe/index/type/1" title="Musiker anmelden">Musiker</a></div>
		<div class="span2"><a class="btn btn-inverse btn-large lightbox" href="/remindMe/index/type/2" title="Auftraggeber anmelden">Auftraggeber</a></div>
	</div>
	<div class="row">
		<figure>
			<img src="public/images/puzzle.png" alt="Puzzle Dir deinen Sound" >
		</figure>
	</div>
	<div class="row">
		<div class="span3 offset4">
			<a class="btn btn-success btn-large lightbox" href="/index/howto" title="So funktioniert's">So funktioniert's</a>
		</div>
		
	</div>

</div>

