<br /><br />
<div id="view-content">
	<h2>Datenschutzerklärung Soundpuzzle</h2>

	<p>1. Soundpuzzle, Philip-Alexander Popp, Behaimstr. 4, 10585 Berlin (in der Folge: Soundpuzzle) dankt für Ihr Interesse an der Webseite und den Dienstleistungen. Natürlich beachtet Soundpuzzle den Schutz Ihrer persönlichen Daten. Wir möchten Sie informieren, wie wir den Datenschutz gewährleisten und welche Daten zu welchem Zweck erhoben werden.</p>

	<p>2. Soundpuzzle nimmt den Schutz Ihrer persönlichen Daten äußerst ernst und hält sich strikt an die Regelungen der Datenschutzgesetzte; insbesondere des Bundesdatenschutzgesetzes und Telemediengesetzes. Personenbezogene Daten werden auf dieser Webseite nur im technisch notwenigen Umfang erhoben; sie werden niemals verkauft oder an Dritte weitergegeben, soweit dies nicht für eine Auftragsbearbeitung notwendig ist. Eine Ausnahme besteht auch im Falle zwingender gesetzlicher Vorschriften, z.B. wenn Daten von staatlichen Stellen, die dazu – insbesondere nach der Strafprozessordnung – berechtigt sind, angefordert werden.
		Eine Speicherung und Verarbeitung Ihrer Daten findet grundsätzlich nur im für eine Auftragsabwicklung erforderlichen Umfang statt.
	</p>
	<h3>Grundsatz der anonymen Datenerhebung</h3>
	<p>
		3. Sie können die von Soundpuzzle betriebene Website ohne Preisgabe Ihrer Identität besuchen.
	</p><p>
		4. Der Zugriff auf diese Webseite wird durch unseren Server protokolliert. Dies erfolgt in erster Linie zu statistischen Zwecken. Folgende Daten werden protokolliert: (1) der Name Ihres Internet Service Providers, (2) die Webseite, von der aus Sie uns besuchen, (3) die Webseite, die Sie bei uns besuchen, (4) der Name der abgerufenen Datei, (5) das Datum und die Uhrzeit des Abrufs, (6) die übertragene Datenmenge, (7) die Meldung über den erfolgreichen Abruf, (8) Ihr Webbrowser, (9) die anfragende Domain sowie (10) die Internet-Protokoll-Adressen der anfragenden Rechner. Sie als Besucher unserer Webseite bleiben jedoch anonym. Eine Zusammenführung dieser Daten mit anderen Datenquellen wird nicht vorgenommen. Die Daten werden zudem nach einer statistischen Auswertung gelöscht.
	</p>

	<h3>Verwendung von Cookies</h3>
	<p>
		5. In einigen Bereichen unserer Webseite setzen wir Cookies ein. Dies sind kleine Textdateien, die durch Ihren Browser auf Ihrem Rechner abgelegt werden. Die Nutzung unserer Webseite ist auch ohne Cookies in vollem Umfang möglich. Sie können Ihren Browser so einstellen, dass er Sie über Cookies informiert, diese akzeptiert oder auch ablehnt.
	</p>

	<h3>Google Analytics</h3>

	<p>6. Es wird auf der Webseite Google Analytics genutzt. Dieser Dienst der Google Inc. verwendet ebenfalls Cookies und ermöglicht die Analyse der Benutzung unserer Webseite.
		Die Informationen über die Nutzung unserer Webseite werden einschließlich Ihrer IP-Adresse an einen Server der Google Inc. übertragen. Google wertet anhand dieser Informationen die Nutzung der Webseite aus und erstellt Berichte hierüber für die Betreiber der Webseite, also uns. Google wird diese Informationen gegebenenfalls an Dritte übertragen, sofern dies vorgeschrieben ist oder Dritte diese Informationen im Auftrag von Google verarbeiten. Google versichert, dass Ihre IP-Adresse nicht mit anderen Daten in Verbindung gebracht wird.
		Durch die Nutzung unserer Webseiten erklären Sie sich mit der Bearbeitung der über Sie erhobenen Daten durch Google in der zuvor beschriebenen Art und Weise und zu dem zuvor benannten Zweck einverstanden. Wenn Sie nicht einverstanden sind, bitten wir Sie, die Annahme von Cookies durch Ihren Browser zu verhindern.
	</p>

	<h3>Externe Links</h3>
	<p>
		8. Auf der Webseite werden Links verwendet, die auf Seiten Dritter verweisen.
		Soundpuzzle hat keinen Einfluss auf den Inhalt und die Gestaltung der Seiten anderer Anbieter und übernimmt keine Haftung für deren Inhalt. Leider kann die eigene Datenschutzerklärung nicht auf diese anderen Seiten ausgeweitet werden. Bitte informieren Sie sich auf den entsprechenden Seiten über die Maßnahmen zum Datenschutz.
	</p>

	<h3>Newsletter</h3>
	<p>
		9. Wir behalten uns das Recht vor, einen Newsletter einzurichten. Wenn Sie den auf der Webseite angebotenen Newsletter empfangen möchten, benötigen wir von Ihnen eine gültige Email-Adresse sowie Informationen, die uns die Überprüfung gestatten, dass Sie der Inhaber der angegebenen Email-Adresse sind bzw. deren Inhaber mit dem Empfang des Newsletters einverstanden ist. Weitere Daten werden nicht erhoben.
	</p>
	<h3>
		Auskunftsrecht
	</h3>
	<p>
		10. Ihre Einwilligung zur Speicherung der Daten, der Email-Adresse sowie deren Nutzung zum Versand des Newsletters können Sie jederzeit widerrufen. Sie haben jederzeit das Recht auf Auskunft über die hinsichtlich Ihrer Person gespeicherten Daten, ihre Herkunft und Empfänger sowie den Zweck der Speicherung. Diesbezügliche Anfragen können Sie richten an popp.philip@googlemail.com.
	</p>
	<h3>
		Datensicherheit
	</h3>
	<p>
		11. Zum Schutz Ihrer bei uns hinterlegten personenbezogenen Daten vor unberechtigtem Zugriff bzw. Missbrauch werden umfangreiche organisatorische, technische und andere Sicherheitsmaßnahmen ergriffen. Es findet eine regelmäßige Überprüfung und Anpassung an den technologischen Fortschritt statt.
	</p>
	<h3>Verwendung von Facebook Social Plugins</h3>
	<p>
		12. Unser Internetauftritt verwendet Social Plugins ("Plugins") des sozialen Netzwerkes facebook.com, welches von der Facebook Inc., 1601 S. California Ave, Palo Alto, CA 94304, USA betrieben wird ("Facebook"). Die Plugins sind an einem der Facebook Logos erkennbar (weißes „f“ auf blauer Kachel oder ein „Daumen hoch“-Zeichen) oder sind mit dem Zusatz "Facebook Social Plugin" gekennzeichnet. Die Liste und das Aussehen der Facebook Social Plugins kann hier eingesehen werden: http://developers.facebook.com/plugins.
		Wenn Sie eine Webseite unseres Internetauftritts aufrufen, die ein solches Plugin enthält, baut Ihr Browser eine direkte Verbindung mit den Servern von Facebook auf. Der Inhalt des Plugins wird von Facebook direkt an Ihren Browser übermittelt und von diesem in die Webseite eingebunden. Wir haben daher keinen Einfluss auf den Umfang der Daten, die Facebook mit Hilfe dieses Plugins erhebt und informieren Sie daher entsprechend unserem Kenntnisstand:
		Durch die Einbindung der Plugins erhält Facebook die Information, dass Sie die entsprechende Seite unseres Internetauftritts aufgerufen haben. Sind Sie bei Facebook eingeloggt, kann Facebook den Besuch Ihrem Facebook-Konto zuordnen. Wenn Sie mit den Plugins interagieren, zum Beispiel den Like Button betätigen oder einen Kommentar abgeben, wird die entsprechende Information von Ihrem Browser direkt an Facebook übermittelt und dort gespeichert. Falls Sie kein Mitglied von Facebook sind, besteht trotzdem die Möglichkeit, dass Facebook Ihre IP-Adresse in Erfahrung bringt und speichert.
		Zweck und Umfang der Datenerhebung und die weitere Verarbeitung und Nutzung der Daten durch Facebook sowie Ihre diesbezüglichen Rechte und Einstellungsmöglichkeiten zum Schutz Ihrer Privatssphäre entnehmen Sie bitte den Datenschutzhinweisen von Facebook: http://www.facebook.com/policy.php.
		Wenn Sie Facebookmitglied sind und nicht möchten, dass Facebook über unseren Internetauftritt Daten über Sie sammelt und mit Ihren bei Facebook gespeicherten Mitgliedsdaten verknüpft, müssen Sie sich vor Ihrem Besuch unseres Internetauftritts bei Facebook ausloggen.
		Ebenfalls ist es möglich Facebook-Social-Plugins mit Add-ons für Ihren Browser zu blocken, zum Beispiel mit dem "Facebook Blocker".
		Weitere Informationen und Kontakt
	</p>
	<p>
		13. Soundpuzzle behält sich das Recht vor, diese Datenschutzerklärung zu ändern. Sie begründet kein vertragliches oder sonstiges formales Recht gegenüber der Soundpuzzle.
	</p>
	<p>
		14. Haben Sie weitere Fragen zum Datenschutz oder Bearbeitung Ihrer Daten oder wünschen Auskunft wenden Sie sich bitte an:
	</p>
	<address>
		<strong>Soundpuzzle</strong><br>
		Philip-Alexander Popp<br>
		Behaimstr. 4<br>
		10585 Berlin<br>
		Telefon: 01577/8948228<br>
		Fax: nicht vorhanden<br>
		E-Mail: popp.philip@googlemail.com<br>

	</address>
	<p>
		Hierhin können Sie Ihre Wünsche zu Auskünften, Löschungen oder Berichtigungen Ihrer Daten senden. Bei der Kommunikation per E-Mail können wir keine vollständige Datensicherheit garantieren. Wir empfehlen für vertrauliche Informationen den Postweg zu nutzen.
	</p>

</div>