<h2>Kennst Du dieses Problem?</h2>
<p>Du arbeitest an einem Musikprojekt aber es fehlt etwas, dass Du nicht selber umsetzen kannst?
	Dafür kann es verschiedene Gründe geben wie das Fehlen der musikalischen Fähigkeit z.B. der Stimme,
	fehlende Inspiration oder einfach um Abwechslung zu schaffen.</p>

<h3>Wie hilft man sich in so einer Situation?</h3>

</p>
<p>
	Meistens muss man auf die wenigen Kontakte zurückgreifen, die man bereits kennt oder in einem
	oftmals unbefriedigendem Prozess nach neuen Partnern suchen.
	Soundpuzzle ändert das!</p>