<?php

switch ($this->step) {
	case 1:
		echo '<div class="step-1">
	<h2>Briefing</h2>
	<p>
	Der Auftraggeber startet  ein neues Projekt und beschreibt in einem Briefing
so gut wie möglich wie sich das Endprodukt anhören soll. Er gibt hierzu relevante Informationen
wie z.B. Text, Geschwindigkeit, Mindestqualität der Aufnahme etc. ein.
Den Preis legt der Auftraggeber selber fest.</p>

<p><strong>	Der Clou:</strong><br>
Der Auftraggeber kann Dateien anzuhängen wie z.B. ein unfertiges Musikstück zu
dem die Beiträge erstellt werden sollen. Die Musiker können es, wenn gewollt auch herunterladen, sodass ein zielgenaues Arbeiten möglich wird.
</p>

</div>';

		break;
	case '2':
		echo '<div class = "step-3 ">
<h2>Der Findungsprozess</h2>
<p>Nachdem ein Projekt im Wettbewerb veröffentlicht wurde haben Musiker nun die Möglichkeit daran teilzunehmen und Beiträge einzureichen. </p><p>Diese kann der Auftraggeber anhören und kommentieren.
So können die Musiker Ihre Beiträge abstimmen und sich der Wunschvorstellung des Auftraggebers so weit wie möglich nähern. </p>

<h3>Schutz der Beiträge</h3>
<p>
Um den Auftraggeber und auch die teilnehmenden Musiker zu schützen werden alle musikalischen 
Beiträge mit einem Voicetag(Musikwasserzeichen) versehen. Dadurch ist ein fast risikoloser Austausch zwischen Auftraggeber und Musiker gewährleistet.</p>
<h3>Der Community-Effekt</h3>
<p>
Der Auftraggeber hat auch die Möglichkeit sein Projekt über soziale Netzwerke zu verbreiten.
Hierbei macht man sich das große Verbreitungspotenzial zu Nutze und lässt andere die Vorschläge bewerten und kommentieren. </p><p>Dadurch wird ein viraler Effekt geschaffen, der bei der Auswahl des am besten passenden Beitrages hilft. Als positiver Nebeneffekt können Auftraggeber sowie Musiker dadurch auch in anderen Kreisen auf sich aufmerksam machen und neue Fans oder Kunden gewinnen.
</p>
</div>';

		break;
	case '3':
		echo '<div class = "step-4 ">
<h2>Wählen des Siegers</h2>
<p>Ist die Projektzeit abgelaufen muss sich der Auftragnehmer für einen Beitrag entscheiden oder
die Projektlaufzeit verlängern.</p><p> Hat er sich für einen Beitrag entschieden findet der Austausch statt.
Der Auftraggeber erhält als Endprodukt die erstellte/n Musikdatei/en im gewünschten Format.
Außerdem erhält per Nutzungsvertrag die vom Musiker übertragenen Verwertungsrechte .
Im Gegenzug erhält der Musiker das Preisgeld.</p>
<h3>Geldzurück-Garantie</h3>
<p>
Gefällt dem Auftraggeber keiner der erstellten Musikbeiträge, wird das gesamte Preisgeld erstattet.
Der Auftraggeber hat also kein Risiko.  </p>
</div>';

		break;
	default:
		break;
}
?>