<?php

switch ($this->step) {
	case 1:
		echo '<div class="step-1">
	<h2>Einstellungsprozess</h2>
	<p>In einem Briefing beschreibst Du so gut wie möglich worum es geht und was gemacht werden soll. Dann lädst Du die Musikdatei  hoch, zu der die eingehenden Musikbeiträge erstellt werden sollen .Dabei gibst Du möglichst viele relevante Informationen wie Geschwindigkeit, Mindestqualität der Aufnahme und Stil etc. an. Du kannst  z.B. auch einen Text vorgeben der eingesungen werden soll.
		Der Kreativität sind hier keine Grenzen gesetzt.</p>

	<p>Im Unterschied zum Beauftragen eines Musikers bis jetzt,  legst Du bei Soundpuzzle das Preisgeld selbst fest. Je nachdem wie hoch Du dieses ansetzt, erhältst Du mehr oder weniger Vorschläge, die dementsprechend professionell sind.</p>

</div>';

		break;
	case '2':
		echo '<div class = "step-2 ">
<h2>Schutz der Musik</h2>
<p>Zum Schutz der Musik wird jeder Beitrag einschließlich dem des Auftraggebers mit einem Musikwasserzeichen (Voicetag)versehen.
Du kannst Song den Musikern Dein unfertiges Projekt also risikolos zum Download anbieten, um ihnen die Arbeit so einfach wie möglich zu gestalten.</p>
</div>';

		break;
	case '3':
		echo '<div class = "step-3 ">
<h2>Der Findungsprozess</h2>
<p>Nun wird der Suchauftrag veröffentlicht. Alle für den Auftrag relevanten Musiker
erhalten eine Nachricht, um den Prozess möglichst schnell und zielgenau zu gestalten.</p>
<p>
Nach kurzer Zeit bekommst Du Musikvorschläge von vielen verschiedenen Musikern.
Diese kannst Du nun einzeln und simultan also gleichzeitig zu Deinem eigenen Beitrag hören.</p>
<h3>Jetzt wird es spannend:</h3>
<p>
Du hast die Möglichkeit, die für dich erstellten Vorschläge zu kommentieren und zu sagen was Dir gefällt und was nicht. Die Musiker werden daraufhin ihren Beitrag optimieren, um sich Deiner Wunschvorstellung so weit wie möglich zu nähern.
Dabei ist die zu dem Preisgeld zusätzliche Motivation des Musikers das Sammeln von Punkten, die er beim Gewinn des Wettbewerbs erhält, um sich später durch einen hohen Rang neue sowie Bestandskunden für neue Aufträge zu sichern.
</p><h3>Die Voting Variante</h3>
<p>
Wie bereits erwähnt kannst Du Dir Hilfe bei Deiner Auswahl des Gewinnerbeitrages holen.
Als Anreiz für das Voting sichert der Auftraggeber den ersten 10% der Voter, die den Gewinnerbeitrag vorausgeahnt haben ein Geschenk z.B. einen kostenlosen Download des Endproduktes zu, den diese dann auf Soundpuzzle finden sobald das Projekt fertiggestellt ist. Die restlichen Voter, die ebenfalls richtig lagen erhalten diesen dann z.B. zum halben Preis. Es liegt dabei ganz an Dir, was du den Votern bereit bist zu geben.
</p><p>
<strong>
Das Voting hat mehrere positive Nebeneffekte.
</strong><br>
Zum einen für Auftraggeber und Auftragnehmer, die durch die Zusammenarbeit Aufmerksamkeit in neuen Fan-Kreisen bekommen und auf potenzielle neue Fans treffen. Einen Zusätzlichen Vorteil hat der Auftraggeber auch noch dadurch, dass er durch die Abstimmung vorab schon ein Feedback hat und so die Reaktionen für sein Produkt testen kann.
Zum anderen für die Voter, die dadurch einen Einfluss auf den Entstehungsprozess eines Werkes von etwas haben, von dem sie ein Fan sind. Darüber hinaus haben Sie auch noch die Möglichkeit auf ein Geschenk.</p>
</div>';

		break;
	case '4':
		echo '<div class = "step-4 ">
<h2>Auswählen des Siegers</h2>
<p>Schlussendlich wählst Du aus den gesammelten Vorschlägen einen Sieger.
Soundpuzzle sorgt dabei für den sicheren Austausch von Preisgeld und Musikprodukt.
Der Musiker erhält das gewonnene Preisgeld und Du die entsprechenden Musikfiles sowie die kompletten Nutzungs- bzw. Exklusivverwertungsrechte für die erstellten Dateien,
 die per Nutzungsvertrag auf Dich übertragen werden.</p>
</div>';

		break;
	case '5':
		echo '<div class = "step-5 ">
<h2>Geld-zurück-Garantie</h2>
<p>Gefällt dem Auftraggeber keiner der vorgeschlagenen Musikbeiträge, wird das Preisgeld erstattet.
Der Auftraggeber hat also kein Risiko.

Eine effektivere und schnellere Möglichkeit risikolos Musik für bestimmte Zwecke erstellen zu lassen
gibt es nicht.</p>
</div>';

		break;

	default:
		break;
}
?>