Soundpuzzle	\n
Danke für Ihr Anmeldung. Bitte aktivieren Sie nun Ihren Account.\n\n

Willkommen, \n
Klicken Sie auf folgenden Link um Ihren Account zu aktivieren.\n
<?php echo $this->link; ?>\n\n


Mit freundlichen Grüßen,\n
Ihr Soundpuzzle Team\n

Diese E-Mail wurde an <?php echo $this->email; ?> gesendet, da Sie sich auf www.soundpuzzle.de angemeldet haben.
\n\n


kontakt@soundpuzzle.de
