
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<title>Neue Anmeldung</title>
	</head>
	<body>
		<center>
			<table width="600" background="#FFFFFF" style="text-align:left;" cellpadding="0" cellspacing="0">
				<tr>
					<td height="18" width="31" style="border-bottom:1px solid #e4e4e4;">
						<div style="line-height: 0px; font-size: 1px; position: absolute;">&nbsp;</div>
					</td>
					<td height="18" width="131">
						<div style="line-height: 0px; font-size: 1px; position: absolute;">&nbsp;</div>
					</td>
					<td height="18" width="466" style="border-bottom:1px solid #e4e4e4;">
						<div style="line-height: 0px; font-size: 1px; position: absolute;">&nbsp;</div>
					</td>
				</tr>
				<tr>
					<td height="2" width="31" style="border-bottom:1px solid #e4e4e4;">
						<div style="line-height: 0px; font-size: 1px; position: absolute;">&nbsp;</div>
					</td>
					<td height="2" width="131">
						<div style="line-height: 0px; font-size: 1px; position: absolute;">&nbsp;</div>
					</td>
					<td height="2" width="466" style="border-bottom:1px solid #e4e4e4;">
						<div style="line-height: 0px; font-size: 1px; position: absolute;">&nbsp;</div>
					</td>
				</tr>
				<!--GREEN STRIPE-->
				<tr>
					<td width="31" bgcolor="#18516c" style="border-top:1px solid #FFF; border-bottom:1px solid #FFF;" height="113">
						<div style="line-height: 0px; font-size: 1px; position: absolute;">&nbsp;</div>
					</td>

					<!--WHITE TEXT AREA-->
					<td width="131" bgcolor="#FFFFFF" style="border-top:1px solid #FFF; text-align:center;" height="113" valign="middle">
						<span style="font-size:25px; font-family:Trebuchet MS, Verdana, Arial; color:#333;">Soundpuzzle</span>
					</td>

					<!--GREEN TEXT AREA-->
					<td bgcolor="#18516c" style="border-top:1px solid #FFF; border-bottom:1px solid #FFF; padding-left:15px;" height="113">
						<span style="color:#FFFFFF; font-size:18px; font-family:Trebuchet MS, Verdana, Arial;">Eine neue Anmeldung auf Soundpuzzle</span>
					</td>
				</tr>

				<!--DOUBLE BORDERS BOTTOM-->
				<tr>
					<td height="3" width="31" style="border-top:1px solid #e4e4e4; border-bottom:1px solid #e4e4e4;">
						<div style="line-height: 0px; font-size: 1px; position: absolute;">&nbsp;</div>
					</td>
					<td height="3" width="131">
						<div style="line-height: 0px; font-size: 1px; position: absolute;">&nbsp;</div>
					</td>
					<td height="3" style="border-top:1px solid #e4e4e4; border-bottom:1px solid #e4e4e4;">
						<div style="line-height: 0px; font-size: 1px; position: absolute;">&nbsp;</div>
					</td>
				</tr>
				<tr>
					<td colspan="3">
						<!--CONTENT STARTS HERE-->
						<br />
						<br />
						<table cellpadding="0" cellspacing="0">
							<tr>
								<td width="15"><div style="line-height: 0px; font-size: 1px; position: absolute;">&nbsp;</div>
								</td>
								<td width="570" style="padding-right:10px; font-family:Trebuchet MS, Verdana, Arial; font-size:12px;" valign="top">
									<span style="font-family:Trebuchet MS, Verdana, Arial; font-size:17px; font-weight:bold;">Neue Anmeldung</span>
									<br />
									<p>E-Mail: <?php echo $this->email; ?></p>
									<p>Typ: <?php echo $this->type; ?> 1 - Musiker; 2 - Auftraggeber</p>
									Mit freundlichen Grüßen,<br/>
									Ihr Admin Team<br/>
									<br/>


								</td>
								
							</tr>
						</table>
					</td>
				</tr>
			</table>
			<br />
			<table cellpadding="0" style="border-top:1px solid #e4e4e4; text-align:center; font-family:Trebuchet MS, Verdana, Arial; font-size:12px;" cellspacing="0" width="600">
				<tr>
					<td height="2" style="border-bottom:1px solid #e4e4e4;">
						<div style="line-height: 0px; font-size: 1px; position: absolute;">&nbsp;</div>
					</td>
				</tr>
				<td style="font-family:Trebuchet MS, Verdana, Arial; font-size:12px;">
					<br />
					kontakt@soundpuzzle.de
				</td>
				</tr>
			</table>
		</center>
	</body>
</html>
