<!-- application/layouts/scripts/layout.phtml -->
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Zend Framework Quickstart Application</title>
  <?php echo $this->headLink()->appendStylesheet('styles/bootstrap.min.css') ?>
  <?php echo $this->headLink()->appendStylesheet('styles/bootstrap-responsive.min.css') ?>
  <?php echo $this->headScript()->prependFile('scripts/bootstrap.min.js'); ?>
</head>
<body>

<?php echo $this->layout()->content ?>

</body>
</html>