<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<title>Zend Framework Quickstart Application</title>
		<base href="<?php echo $this->baseUrl(); ?>" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
			<?php $this->headLink()->appendStylesheet($this->baseUrl() . '/styles/bootstrap.min.css') ?>
			<?php $this->headLink()->appendStylesheet($this->baseUrl() . '/styles/bootstrap-responsive.min.css') ?>
			<?php echo $this->headLink()->appendStylesheet($this->baseUrl() . '/styles/colorbox.css') ?>
	</head>
	<body id="lightbox">
		<div class="container-fluid">
			<?php echo $this->layout()->content ?>
		</div>
		<?php $this->headScript()->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.js'); ?>
		<?php $this->headScript()->appendFile($this->baseUrl() . '/scripts/jquery.colorbox.min.js'); ?>
		<?php $this->headScript()->appendFile($this->baseUrl() . '/scripts/bootstrap.min.js'); ?>
		<?php echo $this->headScript()->appendFile($this->baseUrl() . '/scripts/validation.js'); ?>
	</body>
</html>