<section id="lightbox">
	<div class="container-fluid">
		<?php echo $this->layout()->content ?>
	</div>
	<?php $this->headScript()->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.js'); ?>
	<?php $this->headScript()->appendFile($this->baseUrl() . '/scripts/jquery.colorbox.min.js'); ?>
	<?php $this->headScript()->appendFile($this->baseUrl() . '/scripts/bootstrap.min.js'); ?>
	<?php echo $this->headScript()->appendFile($this->baseUrl() . '/scripts/validation.js'); ?>
</section>